# Problem 0002 - Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
summ = 0
num1 = 1
num2 = 2
temp = 0
while num2 < 4000000:
    print(num1, num2)
    if not num2 % 2:
        summ += num2
    temp = num1 + num2
    num1, num2 = num2, temp

print('sum = ', summ)
# Answer: 4613732
